// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
import "./KeeperBase.sol";
import "./interfaces/KeeperCompatibleInterface.sol";

contract AccuweatherKeeper is KeeperBase, KeeperCompatibleInterface{
    /**
    * Public counter variable
    */
    uint public counter;

    /**
    * Use an interval in seconds and a timestamp to slow execution of Upkeep
    */
    uint public immutable interval;
    uint public lastTimeStamp;

    constructor(uint updateInterval) {
      interval = updateInterval;
      lastTimeStamp = block.timestamp;

      counter = 0;
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        upkeepNeeded = (block.timestamp - lastTimeStamp) > interval;
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
        
        //possible upkeep- using accuweather endpoints
        //upkeepNeeded = (Temperature.Imperial.Value >= 90) || (RelativeHumidity > 85 && Temperature.Imperial.Value >= 90); 
        //IsDayTime == True
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;
            counter = counter + 1;
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }
}